worker_processes  1;
error_log  /var/log/nginx/error.log;
pid        /var/run/nginx.pid;

load_module /etc/nginx/modules/ngx_http_ws_deflate_module.so;

events {
    worker_connections  1024;
}

http {
    access_log  /var/log/nginx/access.log;

    server {
        listen       80;

        location /ws {
            proxy_pass http://backend:9001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;

            ws_deflate on;
            ws_deflate_compression_level 6;
            ws_deflate_context_takeover on;
        }
    }
}
